//////////////////////////////////////////////////////////////
// File:		// WebBrowser.h
// File time:	// 14.02.2006	18:53
// Description: //////////////////////////////////////////////
// 
//

#ifndef _WEBBROWSER_H_UID00000059610C3326
#define _WEBBROWSER_H_UID00000059610C3326

//////////////////////////////////////////////////////////////

CString ResourceToURL(LPCTSTR lpszResourcePath);

//////////////////////////////////////////////////////////////

#pragma pack(push)
#pragma pack(8)

// SimpleBrowser: Web browser control 
//#include "SimpleBrowser.h"

// CWebBrowser2:
// Automatically generated IDispatch wrapper class(es)
// for MS WebBrowser ActiveX control. This file is generated by MS Visual C++ 6.0
#include "webbrowser2.h"

// MFC include header with CHtmlView
//CObject
	//CCmdTarget;
		//CWnd
			//CView
				//CFormView
					//class CHtmlView;
#include <AfxHtml.h>

//////////////////////////////////////////////////////////////
// IHTMLDocument2

#include <Mshtml.h>

//////////////////////////////////////////////////////////////
// smart pointers for IHTMLDocument2 & etc.

//#include <ComDef.h>

//////////////////////////////////////////////////////////////

//CString ResourceToURL(LPCTSTR lpszURL);

#include <atlbase.h>
#include <afxcoll.h>

#pragma pack(pop)

//////////////////////////////////////////////////////////////

#pragma warning( push )
#pragma warning( disable: 4192 )
#pragma warning( disable: 4146 )
//#import "mshtml.tlb"
#pragma warning( pop )

//////////////////////////////////////////////////////////////

#pragma warning( disable : 4711 )

//////////////////////////////////////////////////////////////

class CWebBrowserExtensions
{
public:
	CWebBrowserExtensions( CWebBrowser2* pWebBrowser );
	CWebBrowserExtensions( CHtmlView* pHtmlView );
	CWebBrowserExtensions( IWebBrowser2* pBrowser = NULL );
	~CWebBrowserExtensions();

	BOOL SetBrowser( CWebBrowser2* pWebBrowser );
	BOOL SetBrowser( CHtmlView* pHtmlView );
	BOOL SetBrowser( IWebBrowser2* pBrowser );

	IHTMLDocument2* GetDocument();

/*
	#pragma warning( push )
	#pragma warning( disable: 4192 )
	#pragma warning( disable: 4146 )
	#import "mshtml.tlb"
	#pragma warning( pop )

	#include <AfxHtml.h>
	#include <Mshtml.h>
*/

	MSHTML::IHTMLDocument2Ptr GetDocumentPtr()
	{
		MSHTML::IHTMLDocument2Ptr ptrHtmlDoc = GetDocument();
		if( ptrHtmlDoc != NULL )
		{
			ptrHtmlDoc->Release();
		}
		return ptrHtmlDoc;
	}

	BOOL insertAdjacentHTML( LPCTSTR where, LPCTSTR tagid, LPCTSTR string);
	BOOL replaceInnerHTML( LPCTSTR tagid, LPCTSTR string);
	_bstr_t getInnerHTML( LPCTSTR tagid );

	void Write(LPCTSTR string);
		// append string to current document; note that the WebBrowser control tolerates
		// poorly formed documents, like:

		// <html><body>....
		// --- no trailing body or html tags

		// <html><body>...</body></html><html><body>...</body></html>...
		// --- multiple documents

	void Clear();							
		// clear current document

	void Close();							

    void Refresh();
		// refresh contents

	void Navigate(LPCTSTR URL);
		// navigate to URL

	void NavigateResource(LPCTSTR szResourceName, LPCTSTR szResurceType = NULL );

	// Calls a Script function with a multiple string arguments.
	// Arguments are taken from paramArray.
	bool CallJScript(const CString strFunc, const CStringArray& paramArray, CString *sResult);

	// Calls a Script function with 1 argument that is a VB array of strings.
	// VBArray is array of VT_VARIANT of VT_BSTR.
	bool CallJScript2(const CString strFunc, const CStringArray& paramArray, CString *sResult);

protected:
	BOOL SetBrowserWnd( CWnd* pWnd );

	IWebBrowser2			*m_Browser;          // browser control
    IDispatch               *m_BrowserDispatch;  // browser control 
};

//////////////////////////////////////////////////////////////

#endif //ifndef _WEBBROWSER_H_UID00000059610C3326
