#!/bin/sh

PATH="${PATH}:/home/ror13/src/mxe/usr/bin" ./configure --host=i686-pc-mingw32  --enable-windowsystem=windows --enable-drawsystem=opengl
PATH="${PATH}:/home/ror13/src/mxe/usr/bin" make clean
PATH="${PATH}:/home/ror13/src/mxe/usr/bin" ./configure --host=i686-pc-mingw32  --enable-windowsystem=windows --enable-drawsystem=opengl
PATH="${PATH}:/home/ror13/src/mxe/usr/bin" make 
