/* The following codes are unique to YOUR company. */

#define ValidateCode1 0x9826
#define ValidateCode2 0x50BE
#define ValidateCode3 0x868F
#define ClientIDCode1 0x842C
#define ClientIDCode2 0xF3D1
#define ReadCode1     0xBAA2
#define ReadCode2     0x9848
#define ReadCode3     0xA391
#define WriteCode1    0x6C0E
#define WriteCode2    0x9159
#define WriteCode3    0x1542

#define RemoteUpdateEncryptKey    0xBB487896
