#ifndef MULTIPLE_PRODUCT_H
#pragma once
#endif

///////////////////////////////////////////////////////////////////////////
// WARNING!         WARNING!              WARNING!             WARNING!  //
// This file is the source for automatically generated NSIS header.      //
// It is converted by $/Tools/cpp2nsis tool.                             //
// You shouldn't use much special syntax - it may be converted to NSIS   //
// incorrectly!                                                          //
///////////////////////////////////////////////////////////////////////////
// NOTE! To add new product please follow this comment:
// TODO: Add new product here!
///////////////////////////////////////////////////////////////////////////
// NOTE! To append additional info for all products please follow this comment
// in product.h, Protection folder, Registration folder, NSIS folder:
// TODO: Add new product's info here!
///////////////////////////////////////////////////////////////////////////

#define PRODUCT_APPLIDEV			1
#define PRODUCT_APPLICA				2
//{{AXPDEL
#define PRODUCT_MULTISTATION		3
#define PRODUCT_ZEROLINK			4
#define PRODUCT_PRESENTER			5
#define PRODUCT_IPCLONE				6
#define PRODUCT_APPLICASERVER		7
#define PRODUCT_SNIFFER				8
#define PRODUCT_ZSERVER				9
#define PRODUCT_MANYPC				10
#define PRODUCT_CVNET				11
#define PRODUCT_PRESENTER_SIGNAGE	12
#define PRODUCT_PRESENTER_WALL		13
#define PRODUCT_PROVISUAL			15
#define PRODUCT_PRESENTER3			16
#define PRODUCT_PRESENTER_PRO		17
#define PRODUCT_PRESENTER_SIGNWARE 	18
#define PRODUCT_SIGNIA				19
#define PRODUCT_SIGNWALL			20
//}}AXPDEL
// TODO: Add new product here!

#define FAMILY_APPLICA			1
//{{AXPDEL
#define FAMILY_PRESENTER		2
#define FAMILY_IPCLONE			3
#define FAMILY_APPLICA_SERVER		4
#define FAMILY_SNIFFER			5
//}}AXPDEL
// TODO: Add new product here!

// NSIS_COMMENT_START

#ifdef MULTIPLE_PRODUCT_H
#undef PRODUCT_NAME
#undef PRODUCT_VERSION
#undef PRODUCT_MAJOR_VERSION
#undef PRODUCT_MINOR_VERSION
#undef PRODUCT_SUBMINOR_VERSION
#undef PRODUCT_VERSION_APPENDIX
#undef PRODUCT_URL_NAME
#undef PRODUCT_SUPPORT_URL_NAME
#undef PRODUCT_COMPANY
#undef PRODUCT_COPYRIGHT
#undef PRODUCT_GUID
#undef PRODUCT_REBOOT_REQUIRED
#undef PRODUCT_REGISTRATION_URL
#undef PRODUCT_PROTECTION_NAME
#undef PRODUCT_SERIAL_PREFIX
//{{AXPDEL
//#undef PRODUCT_DEFAULT_LICENSES
//}}AXPDEL
#undef PRODUCT_USES_LICENSES
// TODO: Add new product's info here!

#undef APPLICA_ICON
#undef APPLICA_BMP
#endif // ifdef MULTIPLE_PRODUCT_H

#ifndef PRODUCT_H_COMMON_DEFINES

#if APPLICA_PRODUCT==PRODUCT_APPLIDEV
#define PRODUCT_APPLIDEV_DEFINE
#endif

#if APPLICA_PRODUCT==PRODUCT_APPLICA
#define PRODUCT_APPLICA_DEFINE
#endif

//{{AXPDEL
#if APPLICA_PRODUCT==PRODUCT_MANYPC
#define PRODUCT_MANYPC_DEFINE
#endif

#if APPLICA_PRODUCT==PRODUCT_CVNET
#define PRODUCT_CVNET_DEFINE
#endif

#if APPLICA_PRODUCT==PRODUCT_MULTISTATION
#define PRODUCT_MULTISTATION_DEFINE
#endif

#if APPLICA_PRODUCT==PRODUCT_ZEROLINK
#define PRODUCT_ZEROLINK_DEFINE
#endif

#if APPLICA_PRODUCT==PRODUCT_APPLICASERVER
#define PRODUCT_APPLICASERVER_DEFINE
#endif

#if APPLICA_PRODUCT==PRODUCT_ZSERVER
#define PRODUCT_ZSERVER_DEFINE
#endif

#if APPLICA_PRODUCT==PRODUCT_PRESENTER
#define PRODUCT_PRESENTER_DEFINE
#endif

#if APPLICA_PRODUCT==PRODUCT_PRESENTER_SIGNAGE
#define PRODUCT_PRESENTER_SIGNAGE_DEFINE
#endif

#if APPLICA_PRODUCT==PRODUCT_PRESENTER_SIGNWARE
#define PRODUCT_PRESENTER_SIGNWARE_DEFINE
#endif

#if APPLICA_PRODUCT==PRODUCT_PRESENTER_WALL
#define PRODUCT_PRESENTER_WALL_DEFINE
#endif

#if APPLICA_PRODUCT==PRODUCT_PRESENTER3
#define PRODUCT_PRESENTER_3_DEFINE
#endif

#if APPLICA_PRODUCT==PRODUCT_PRESENTER_PRO
#define PRODUCT_PRESENTER_PRO_DEFINE
#endif

#if APPLICA_PRODUCT==PRODUCT_PRESENTERPRO
#define PRODUCT_PRESENTER_PRO_DEFINE
#endif

#if APPLICA_PRODUCT==PRODUCT_PROVISUAL
#define PRODUCT_PROVISUAL_DEFINE
#endif

#if APPLICA_PRODUCT==PRODUCT_IPCLONE
#define PRODUCT_IPCLONE_DEFINE
#endif

#if APPLICA_PRODUCT==PRODUCT_SNIFFER
#define PRODUCT_SNIFFER_DEFINE
#endif

#if APPLICA_PRODUCT==PRODUCT_SIGNIA
#define PRODUCT_SIGNIA_DEFINE
#endif

#if APPLICA_PRODUCT==PRODUCT_SIGNWALL
#define PRODUCT_SIGNWALL_DEFINE
#endif
//}}AXPDEL

// TODO: Add new product here!

#endif //ifndef PRODUCT_H_COMMON_DEFINES

// NSIS_COMMENT_END

#define REGISTRATION_URL_ARGUMNETS	_T("&serial=<<<SERIAL>>>&acode=<<<AUTH_CODE>>>") // &NAME=Vasya%20Pupkin&COMPANY=My%20Company

#define PRODUCT_GUID_LIST			_T("{1BEF666B-036C-4FEF-95B2-DEAD44451234}")

#define PRODUCT_GUID_APPLICA		_T("{ABCCCED3-A852-4beb-9D49-0D0E76F6E64D}")
//{{AXPDEL
#define PRODUCT_GUID_PRESENTER		_T("{19E72666-6C1E-4666-83B5-B3F863639A8E}")
#define PRODUCT_GUID_PRESENTER_SIGNAGE	_T("{11C77844-AE6A-404c-96AA-FF55EB13E159}")
#define PRODUCT_GUID_PRESENTER_SIGNWARE _T("{11D01885-3E02-436e-BBC0-0D1645C0ABCF}")
#define PRODUCT_GUID_PRESENTER_WALL	_T("{1E241F63-BC20-4ce5-9ECD-DB181A4F9274}")
#define PRODUCT_GUID_PRESENTER_3	_T("{1D1FFE9B-2CE9-4e3e-B827-6F96861DFA3B}")
#define PRODUCT_GUID_PRESENTER_PRO	_T("{134D99AD-4514-468f-ACB9-489FFCEFB425}")
#define PRODUCT_GUID_PROVISUAL		_T("{1130930E-CB2C-4fa2-BAA6-ABF280011BF3}")
#define PRODUCT_GUID_IPCLONE		_T("{200400B9-BCC9-4217-A88D-5BEFC7E4D122}")
#define PRODUCT_GUID_APPLICA_SERVER	_T("{ED70158B-B24A-4d93-A125-EE9E144B811A}")
#define PRODUCT_GUID_SNIFFER		_T("{D15BEEFF-DEAD-4B71-A0AA-55E11074D0E7}")
#define PRODUCT_GUID_SIGNIA		_T("{DE0F4778-C551-4978-A8B4-331F5B2CFA29}")
#define PRODUCT_GUID_SIGNWALL		_T("{F9F4A1F6-8C67-4b7d-86DE-7954B8DE1911}")
//}}AXPDEL
// TODO: Add new product here!

//{{AXPDEL
#ifdef DEMO_VERSION
#define g_szProductTrialStr _T("Tr")
#else
#ifdef APPLICA_LITE
#define g_szProductTrialStr _T("Lt")
#else
//}}AXPDEL
#define g_szProductTrialStr _T("")
//{{AXPDEL
#endif
#endif
//}}AXPDEL

//////////////////////////////////////////////////////////////////////////

//{{AXPDEL
#define PRODUCT_SERIAL_SUPER_PREFIX	_T("UNLM")
//}}AXPDEL

//////////////////////////////////////////////////////////////////////////

// Don't use the following defines outside this header!!!
// Use PRODUCT_VERSION, PRODUCT_MAJOR_VERSION, etc. instead!!!

#define PRODUCT_APPLICA_VERSION				"5.2"
#define PRODUCT_APPLICA_MAJOR_VERSION		5
#define PRODUCT_APPLICA_MINOR_VERSION		2
#define PRODUCT_APPLICA_SUBMINOR_VER		0
#define	PRODUCT_APPLICA_VERSION_APPENDIX	""

#define PRODUCT_APPLICA_URL_NAME			"www.applica.com"
#define PRODUCT_APPLICA_SUPPORT_URL_NAME	"support@applica.com"
#define PRODUCT_APPLICA_COMPANY				"Applica, Inc."
//{{AXPDEL
#define PRODUCT_APPLICA_REG_PREFIX			_T("http://applica.biz/registration?product=")

#define PRODUCT_MANYPC_URL_NAME				"www.manypc.com"
#define PRODUCT_MANYPC_SUPPORT_URL_NAME		"support@manypc.com"
#define PRODUCT_MANYPC_COMPANY				"ManyPC, Inc."
#define PRODUCT_MANYPC_REG_PREFIX			_T("http://manypc.com/registration?product=")

#define PRODUCT_CVNET_URL_NAME				"www.cvnet.com"
#define PRODUCT_CVNET_SUPPORT_URL_NAME		"support@cvnet.com"
#define PRODUCT_CVNET_COMPANY				"CVnet"
#define PRODUCT_CVNET_REG_PREFIX			_T("http://applica.biz/registration?product=")

#define PRODUCT_ZEROLINK_SUPPORT_URL_NAME	"support@trsc.net"
#define PRODUCT_ZEROLINK_COMPANY			"TekResource Service Corp."
//}}AXPDEL

//{{AXPDEL
#ifdef PRODUCT_APPLICA_CHINA
//}}AXPDEL
#define PRODUCT_APPLICA_REG_PREFIX			_T("http://www.applicachina.com/registration?product=")
//{{AXPDEL
#endif // PRODUCT_APPLICA_CHINA
//}}AXPDEL
//////////////////////////////////////////////////////////////////////////

#define PRODUCT_ROOT		REG_HKLM

//////////////////////////////////////////////////////////////////////////

#ifndef PRODUCT_H_COMMON_DEFINES

//////////////////////////////////////////////////////////////////////////

#define PRODUCT_URL					"http://" PRODUCT_URL_NAME
#define PRODUCT_SUPPORT_URL			"mailto:" PRODUCT_SUPPORT_URL_NAME

#define PRODUCT_FULL_NAME			PRODUCT_NAME " v." PRODUCT_VERSION PRODUCT_VERSION_APPENDIX

#define PRODUCT_KEY		_T("SYSTEM\\CurrentControlSet\\Control\\") PRODUCT_GUID
#define PRODUCT_KEY_UP		_T("SYSTEM\\CurrentControlSet\\Control")

//{{AXPDEL
// PRODUCT_DEFAULT_LICENSES may vary from 0 to 31
//#define PRODUCT_DEFAULT_LICENSES	31
//}}AXPDEL

//////////////////////////////////////////////////////////////////////////

#ifdef PRODUCT_APPLIDEV_DEFINE
#define PRODUCT_NAME				"AppliDev"
#define PRODUCT_VERSION				PRODUCT_APPLICA_VERSION
#define PRODUCT_MAJOR_VERSION		PRODUCT_APPLICA_MAJOR_VERSION
#define PRODUCT_MINOR_VERSION		PRODUCT_APPLICA_MINOR_VERSION
#define PRODUCT_SUBMINOR_VERSION	PRODUCT_APPLICA_SUBMINOR_VER
#define PRODUCT_VERSION_APPENDIX	PRODUCT_APPLICA_VERSION_APPENDIX
#define PRODUCT_URL_NAME			PRODUCT_APPLICA_URL_NAME
#define PRODUCT_SUPPORT_URL_NAME	PRODUCT_APPLICA_SUPPORT_URL_NAME
#define PRODUCT_COMPANY				PRODUCT_APPLICA_COMPANY
#define PRODUCT_COPYRIGHT			"Copyright (C) Applica, Inc. 1987-2012"
#define PRODUCT_GUID				PRODUCT_GUID_APPLICA
#define PRODUCT_REBOOT_REQUIRED		1
#define PRODUCT_REGISTRATION_URL	PRODUCT_APPLICA_REG_PREFIX _T("APPLIDEV") REGISTRATION_URL_ARGUMNETS
#define PRODUCT_PROTECTION_NAME		_T("AppliDev") g_szProductTrialStr
#define PRODUCT_SERIAL_PREFIX		_T("APDV")
#define PRODUCT_USES_LICENSES		1
// TODO: Add new product's info here!
#endif

#ifdef PRODUCT_APPLICA_DEFINE
#define PRODUCT_NAME				"ApplicaXP"
#define PRODUCT_VERSION				PRODUCT_APPLICA_VERSION
#define PRODUCT_MAJOR_VERSION		PRODUCT_APPLICA_MAJOR_VERSION
#define PRODUCT_MINOR_VERSION		PRODUCT_APPLICA_MINOR_VERSION
#define PRODUCT_SUBMINOR_VERSION	PRODUCT_APPLICA_SUBMINOR_VER
#define PRODUCT_VERSION_APPENDIX	PRODUCT_APPLICA_VERSION_APPENDIX
#define PRODUCT_URL_NAME			PRODUCT_APPLICA_URL_NAME
#define PRODUCT_SUPPORT_URL_NAME	PRODUCT_APPLICA_SUPPORT_URL_NAME
#define PRODUCT_COMPANY				PRODUCT_APPLICA_COMPANY
#define PRODUCT_COPYRIGHT			"Copyright (C) Applica, Inc. 1998-2012, Portions Copyright (C) Microsoft Corporation 1988-2000"
#define PRODUCT_GUID				PRODUCT_GUID_APPLICA
#define PRODUCT_REBOOT_REQUIRED		1
#define PRODUCT_REGISTRATION_URL	PRODUCT_APPLICA_REG_PREFIX _T("APPLICA_XP") REGISTRATION_URL_ARGUMNETS
#define PRODUCT_PROTECTION_NAME		_T("ApplicaXP") g_szProductTrialStr
#define PRODUCT_SERIAL_PREFIX		_T("APXP")
#define PRODUCT_USES_LICENSES		1
// TODO: Add new product's info here!
#endif

//{{AXPDEL
#ifdef PRODUCT_MANYPC_DEFINE
#define PRODUCT_NAME				"Many PC"
#define PRODUCT_VERSION				PRODUCT_APPLICA_VERSION
#define PRODUCT_MAJOR_VERSION		PRODUCT_APPLICA_MAJOR_VERSION
#define PRODUCT_MINOR_VERSION		PRODUCT_APPLICA_MINOR_VERSION
#define PRODUCT_SUBMINOR_VERSION	PRODUCT_APPLICA_SUBMINOR_VER
#define PRODUCT_VERSION_APPENDIX	PRODUCT_APPLICA_VERSION_APPENDIX
#define PRODUCT_URL_NAME			"www.manypc.com"
#define PRODUCT_SUPPORT_URL_NAME	"support@manypc.com"
#define PRODUCT_COMPANY				"Many PC Company"
#define PRODUCT_COPYRIGHT			"Copyright (C) 2004-2012"
#define PRODUCT_GUID				PRODUCT_GUID_APPLICA
#define PRODUCT_REBOOT_REQUIRED		1
#define PRODUCT_REGISTRATION_URL	PRODUCT_MANYPC_REG_PREFIX _T("MANYPC") REGISTRATION_URL_ARGUMNETS
#define PRODUCT_PROTECTION_NAME		_T("ManyPC") g_szProductTrialStr
#define PRODUCT_SERIAL_PREFIX		_T("MNPC")
#define PRODUCT_USES_LICENSES		1
// TODO: Add new product's info here!
#endif

#ifdef PRODUCT_CVNET_DEFINE
#define PRODUCT_NAME				"CVnet"
#define PRODUCT_VERSION				PRODUCT_APPLICA_VERSION
#define PRODUCT_MAJOR_VERSION		PRODUCT_APPLICA_MAJOR_VERSION
#define PRODUCT_MINOR_VERSION		PRODUCT_APPLICA_MINOR_VERSION
#define PRODUCT_SUBMINOR_VERSION	PRODUCT_APPLICA_SUBMINOR_VER
#define PRODUCT_VERSION_APPENDIX	PRODUCT_APPLICA_VERSION_APPENDIX
#define PRODUCT_URL_NAME			"www.cvnet.com"
#define PRODUCT_SUPPORT_URL_NAME	"support@cvnet.com"
#define PRODUCT_COMPANY				"CVnet Company"
#define PRODUCT_COPYRIGHT			"Copyright (C) 2004-2012"
#define PRODUCT_GUID				PRODUCT_GUID_APPLICA
#define PRODUCT_REBOOT_REQUIRED		1
#define PRODUCT_REGISTRATION_URL	PRODUCT_APPLICA_REG_PREFIX _T("CVNET") REGISTRATION_URL_ARGUMNETS
#define PRODUCT_PROTECTION_NAME		_T("CVnet") g_szProductTrialStr
#define PRODUCT_SERIAL_PREFIX		_T("CVNT")
#define PRODUCT_USES_LICENSES		1
// TODO: Add new product's info here!
#endif

#ifdef PRODUCT_MULTISTATION_DEFINE
#define PRODUCT_NAME				"MultiStation PC"
#define PRODUCT_VERSION				PRODUCT_APPLICA_VERSION
#define PRODUCT_MAJOR_VERSION		PRODUCT_APPLICA_MAJOR_VERSION
#define PRODUCT_MINOR_VERSION		PRODUCT_APPLICA_MINOR_VERSION
#define PRODUCT_SUBMINOR_VERSION	PRODUCT_APPLICA_SUBMINOR_VER
#define PRODUCT_VERSION_APPENDIX	PRODUCT_APPLICA_VERSION_APPENDIX
#define PRODUCT_URL_NAME			"www.rose.com"
#define PRODUCT_SUPPORT_URL_NAME	"techsupport@rose.com"
#define PRODUCT_COMPANY				"Rose Electronics"
#define PRODUCT_COPYRIGHT			"Copyright (C) 2004-2012"
#define PRODUCT_GUID				PRODUCT_GUID_APPLICA
#define PRODUCT_REBOOT_REQUIRED		1
#define PRODUCT_REGISTRATION_URL	_T("http://www.rose.com/htm/multistationpc-online-registration.htm")
#define PRODUCT_PROTECTION_NAME		_T("MultiStation") g_szProductTrialStr
#define PRODUCT_SERIAL_PREFIX		_T("MSXP")
#define PRODUCT_USES_LICENSES		1
// TODO: Add new product's info here!
#endif

#ifdef PRODUCT_ZEROLINK_DEFINE
#define PRODUCT_NAME				"ZeroLinkXP"
#define PRODUCT_VERSION				PRODUCT_APPLICA_VERSION
#define PRODUCT_MAJOR_VERSION		PRODUCT_APPLICA_MAJOR_VERSION
#define PRODUCT_MINOR_VERSION		PRODUCT_APPLICA_MINOR_VERSION
#define PRODUCT_SUBMINOR_VERSION	PRODUCT_APPLICA_SUBMINOR_VER
#define PRODUCT_VERSION_APPENDIX	PRODUCT_APPLICA_VERSION_APPENDIX
#define PRODUCT_URL_NAME			"www.tekresource.com/zerolink.htm"
#define PRODUCT_SUPPORT_URL_NAME	PRODUCT_ZEROLINK_SUPPORT_URL_NAME
#define PRODUCT_COMPANY				PRODUCT_ZEROLINK_COMPANY
#define PRODUCT_COPYRIGHT			"Copyright (C) 2004-2012"
#define PRODUCT_GUID				PRODUCT_GUID_APPLICA
#define PRODUCT_REBOOT_REQUIRED		1
#define PRODUCT_REGISTRATION_URL	PRODUCT_APPLICA_REG_PREFIX _T("ZEROLINK") REGISTRATION_URL_ARGUMNETS
#define PRODUCT_PROTECTION_NAME		_T("ZeroLinkXP") g_szProductTrialStr
#define PRODUCT_SERIAL_PREFIX		_T("ZLXP")
#define PRODUCT_USES_LICENSES		1
// TODO: Add new product's info here!
#endif

#ifdef PRODUCT_APPLICASERVER_DEFINE
#define PRODUCT_NAME				"ApplicaServer"
#define PRODUCT_VERSION				"1.1"
#define PRODUCT_MAJOR_VERSION		1
#define PRODUCT_MINOR_VERSION		1
#define PRODUCT_SUBMINOR_VERSION	0
#define PRODUCT_VERSION_APPENDIX	""
#define PRODUCT_URL_NAME			"www.applica.com/product_server.shtml"
#define PRODUCT_SUPPORT_URL_NAME	PRODUCT_APPLICA_SUPPORT_URL_NAME
#define PRODUCT_COMPANY				PRODUCT_APPLICA_COMPANY
#define PRODUCT_COPYRIGHT			"Copyright (C) Applica, Inc. 2005-2012"
#define PRODUCT_GUID				PRODUCT_GUID_APPLICA_SERVER
#define PRODUCT_REBOOT_REQUIRED		1
#define PRODUCT_REGISTRATION_URL	PRODUCT_APPLICA_REG_PREFIX _T("APPLICA_SERVER") REGISTRATION_URL_ARGUMNETS
#define PRODUCT_PROTECTION_NAME		_T("ApplicaServer") g_szProductTrialStr
#define PRODUCT_SERIAL_PREFIX		_T("APSE")
#define PRODUCT_USES_LICENSES		1
// TODO: Add new product's info here!
#endif

#ifdef PRODUCT_ZSERVER_DEFINE
#define PRODUCT_NAME				"ZServer"
#define PRODUCT_VERSION				"1.1"
#define PRODUCT_MAJOR_VERSION		1
#define PRODUCT_MINOR_VERSION		1
#define PRODUCT_SUBMINOR_VERSION	0
#define PRODUCT_VERSION_APPENDIX	""
#define PRODUCT_URL_NAME			"www.tekresource.com/zlink-server.htm"
#define PRODUCT_SUPPORT_URL_NAME	PRODUCT_ZEROLINK_SUPPORT_URL_NAME
#define PRODUCT_COMPANY				PRODUCT_ZEROLINK_COMPANY
#define PRODUCT_COPYRIGHT			"Copyright (C) 2005-2012"
#define PRODUCT_GUID				PRODUCT_GUID_APPLICA_SERVER
#define PRODUCT_REBOOT_REQUIRED		1
#define PRODUCT_REGISTRATION_URL	PRODUCT_APPLICA_REG_PREFIX _T("ZSERVER") REGISTRATION_URL_ARGUMNETS
#define PRODUCT_PROTECTION_NAME		_T("ZServer") g_szProductTrialStr
#define PRODUCT_SERIAL_PREFIX		_T("ZSRV")
#define PRODUCT_USES_LICENSES		1
// TODO: Add new product's info here!
#endif

#ifdef PRODUCT_PRESENTER_DEFINE
#define PRODUCT_NAME				"Presenter2"
#define PRODUCT_VERSION				"2.4"
#define PRODUCT_MAJOR_VERSION		2
#define PRODUCT_MINOR_VERSION		4
#define PRODUCT_SUBMINOR_VERSION	0
#define PRODUCT_VERSION_APPENDIX	""
#define PRODUCT_URL_NAME			"www.applica.com/product_presenter.shtml"
#define PRODUCT_SUPPORT_URL_NAME	PRODUCT_APPLICA_SUPPORT_URL_NAME
#define PRODUCT_COMPANY				PRODUCT_APPLICA_COMPANY
#define PRODUCT_COPYRIGHT			"Copyright (C) Applica, Inc. 2005-2012"
#define PRODUCT_GUID				PRODUCT_GUID_PRESENTER
#define PRODUCT_REBOOT_REQUIRED		0
#define PRODUCT_REGISTRATION_URL	PRODUCT_APPLICA_REG_PREFIX _T("PRESENTER") REGISTRATION_URL_ARGUMNETS
#define PRODUCT_PROTECTION_NAME		_T("Presenter") g_szProductTrialStr
#define PRODUCT_SERIAL_PREFIX		_T("PRES")
#define PRODUCT_USES_LICENSES		1
// TODO: Add new product's info here!
#endif

#ifdef PRODUCT_IPCLONE_DEFINE
#define PRODUCT_NAME				"IpClone"
#define PRODUCT_VERSION				"1.4"
#define PRODUCT_MAJOR_VERSION		1
#define PRODUCT_MINOR_VERSION		4
#define PRODUCT_SUBMINOR_VERSION	0
#define PRODUCT_VERSION_APPENDIX	""
#define PRODUCT_URL_NAME			PRODUCT_APPLICA_URL_NAME
#define PRODUCT_SUPPORT_URL_NAME	PRODUCT_APPLICA_SUPPORT_URL_NAME
#define PRODUCT_COMPANY				PRODUCT_APPLICA_COMPANY
#define PRODUCT_COPYRIGHT			"Copyright (C) Applica, Inc. 2005-2012"
#define PRODUCT_GUID				PRODUCT_GUID_IPCLONE
#define PRODUCT_REBOOT_REQUIRED		0
#define PRODUCT_REGISTRATION_URL	PRODUCT_APPLICA_REG_PREFIX _T("IPCLONE") REGISTRATION_URL_ARGUMNETS
#define PRODUCT_PROTECTION_NAME		_T("IpClone") g_szProductTrialStr
#define PRODUCT_SERIAL_PREFIX		_T("IPCL")
#define PRODUCT_USES_LICENSES		1
// TODO: Add new product's info here!
#endif

#ifdef PRODUCT_SNIFFER_DEFINE
#define PRODUCT_NAME				"Sniffer"
#define PRODUCT_VERSION				"1.2"
#define PRODUCT_MAJOR_VERSION		1
#define PRODUCT_MINOR_VERSION		2
#define PRODUCT_SUBMINOR_VERSION	0
#define PRODUCT_VERSION_APPENDIX	" demo 2"
#define PRODUCT_URL_NAME			PRODUCT_APPLICA_URL_NAME
#define PRODUCT_SUPPORT_URL_NAME	PRODUCT_APPLICA_SUPPORT_URL_NAME
#define PRODUCT_COMPANY				PRODUCT_APPLICA_COMPANY
#define PRODUCT_COPYRIGHT			"Copyright (C) Applica, Inc. 2005-2012"
#define PRODUCT_GUID				PRODUCT_GUID_SNIFFER
#define PRODUCT_REBOOT_REQUIRED		0
#define PRODUCT_REGISTRATION_URL	PRODUCT_APPLICA_REG_PREFIX _T("SNIFFER") REGISTRATION_URL_ARGUMNETS
#define PRODUCT_PROTECTION_NAME		_T("Sniffer") g_szProductTrialStr
#define PRODUCT_SERIAL_PREFIX		_T("SNIF")
#define PRODUCT_USES_LICENSES		0
// TODO: Add new product's info here!
#endif

#ifdef PRODUCT_PRESENTER_SIGNAGE_DEFINE
#define PRODUCT_NAME				"SignagePro"
#define PRODUCT_VERSION				"4.8.2"
#define PRODUCT_MAJOR_VERSION		4
#define PRODUCT_MINOR_VERSION		8
#define PRODUCT_SUBMINOR_VERSION	2
#define PRODUCT_VERSION_APPENDIX	""
#define PRODUCT_URL_NAME			"www.smart-avi.com/categories/digital-signage/signagepro.htm"
#define PRODUCT_SUPPORT_URL_NAME	PRODUCT_APPLICA_SUPPORT_URL_NAME
#define PRODUCT_COMPANY				PRODUCT_APPLICA_COMPANY
#define PRODUCT_COPYRIGHT			"Copyright (C) Applica, Inc. 2005-2012"
#define PRODUCT_GUID				PRODUCT_GUID_PRESENTER_SIGNAGE
#define PRODUCT_REBOOT_REQUIRED		0
#define PRODUCT_REGISTRATION_URL	PRODUCT_APPLICA_REG_PREFIX _T("PRESENTER_SIGNAGE") REGISTRATION_URL_ARGUMNETS
#define PRODUCT_PROTECTION_NAME		_T("SignageServer") g_szProductTrialStr
#define PRODUCT_SERIAL_PREFIX		_T("PREN")
#define PRODUCT_USES_LICENSES		1
// TODO: Add new product's info here!
#endif

#ifdef PRODUCT_PRESENTER_SIGNWARE_DEFINE
#define PRODUCT_NAME				"Signware"
#define PRODUCT_VERSION				"1.3.0"
#define PRODUCT_MAJOR_VERSION		1
#define PRODUCT_MINOR_VERSION		3
#define PRODUCT_SUBMINOR_VERSION	0
#define PRODUCT_VERSION_APPENDIX	""
#define PRODUCT_URL_NAME			"www.applica.com/product_presenter.shtml"
#define PRODUCT_SUPPORT_URL_NAME	PRODUCT_APPLICA_SUPPORT_URL_NAME
#define PRODUCT_COMPANY				PRODUCT_APPLICA_COMPANY
#define PRODUCT_COPYRIGHT			"Copyright (C) Applica, Inc. 2005-2012"
#define PRODUCT_GUID				PRODUCT_GUID_PRESENTER_SIGNWARE
#define PRODUCT_REBOOT_REQUIRED		0
#define PRODUCT_REGISTRATION_URL	PRODUCT_APPLICA_REG_PREFIX _T("PRESENTER_SIGNWARE") REGISTRATION_URL_ARGUMNETS
#define PRODUCT_PROTECTION_NAME		_T("SignwareServer") g_szProductTrialStr
#define PRODUCT_SERIAL_PREFIX		_T("PRSW")
#define PRODUCT_USES_LICENSES		1
// TODO: Add new product's info here!
#endif

#ifdef PRODUCT_PRESENTER_WALL_DEFINE
#define PRODUCT_NAME				"PresenterWALL"
#define PRODUCT_VERSION				"4.8.1"
#define PRODUCT_MAJOR_VERSION		4
#define PRODUCT_MINOR_VERSION		8
#define PRODUCT_SUBMINOR_VERSION	1
#define PRODUCT_VERSION_APPENDIX	""
#define PRODUCT_URL_NAME			"www.applica.com/product_presenter.shtml"
#define PRODUCT_SUPPORT_URL_NAME	PRODUCT_APPLICA_SUPPORT_URL_NAME
#define PRODUCT_COMPANY				PRODUCT_APPLICA_COMPANY
#define PRODUCT_COPYRIGHT			"Copyright (C) Applica, Inc. 2005-2012"
#define PRODUCT_GUID				PRODUCT_GUID_PRESENTER_WALL
#define PRODUCT_REBOOT_REQUIRED		0
#define PRODUCT_REGISTRATION_URL	PRODUCT_APPLICA_REG_PREFIX _T("PRESENTER_WALL") REGISTRATION_URL_ARGUMNETS
#define PRODUCT_PROTECTION_NAME		_T("PresenterWALL") g_szProductTrialStr
#define PRODUCT_SERIAL_PREFIX		_T("PREW")
#define PRODUCT_USES_LICENSES		1
// TODO: Add new product's info here!
#endif

#ifdef PRODUCT_PRESENTER_3_DEFINE
#define PRODUCT_NAME				"Presenter3"
#define PRODUCT_VERSION				"3.0"
#define PRODUCT_MAJOR_VERSION		3
#define PRODUCT_MINOR_VERSION		0
#define PRODUCT_SUBMINOR_VERSION	0
#define PRODUCT_VERSION_APPENDIX	""
#define PRODUCT_URL_NAME			"www.applica.com/product_presenter.shtml"
#define PRODUCT_SUPPORT_URL_NAME	PRODUCT_APPLICA_SUPPORT_URL_NAME
#define PRODUCT_COMPANY				PRODUCT_APPLICA_COMPANY
#define PRODUCT_COPYRIGHT			"Copyright (C) Applica, Inc. 2005-2006"
#define PRODUCT_GUID				PRODUCT_GUID_PRESENTER_3
#define PRODUCT_REBOOT_REQUIRED		0
#define PRODUCT_REGISTRATION_URL	PRODUCT_APPLICA_REG_PREFIX _T("PRESENTER3") REGISTRATION_URL_ARGUMNETS
#define PRODUCT_PROTECTION_NAME		_T("Presenter3") g_szProductTrialStr
#define PRODUCT_SERIAL_PREFIX		_T("PRE3")
#define PRODUCT_USES_LICENSES		1
// TODO: Add new product's info here!
#endif

#ifdef PRODUCT_PRESENTER_PRO_DEFINE
#define PRODUCT_NAME				"PresenterPro"
#define PRODUCT_VERSION				"4.3.1"
#define PRODUCT_MAJOR_VERSION		4
#define PRODUCT_MINOR_VERSION		3
#define PRODUCT_SUBMINOR_VERSION	1
#define PRODUCT_VERSION_APPENDIX	""
#define PRODUCT_URL_NAME			"www.applica.com/product_presenter.shtml"
#define PRODUCT_SUPPORT_URL_NAME	PRODUCT_APPLICA_SUPPORT_URL_NAME
#define PRODUCT_COMPANY				PRODUCT_APPLICA_COMPANY
#define PRODUCT_COPYRIGHT			"Copyright (C) Applica, Inc. 2005-2012"
#define PRODUCT_GUID				PRODUCT_GUID_PRESENTER_PRO
#define PRODUCT_REBOOT_REQUIRED		0
#define PRODUCT_REGISTRATION_URL	PRODUCT_APPLICA_REG_PREFIX _T("PRESENTERPRO") REGISTRATION_URL_ARGUMNETS
#define PRODUCT_PROTECTION_NAME		_T("PresenterPro") g_szProductTrialStr
#define PRODUCT_SERIAL_PREFIX		_T("PREP")
#define PRODUCT_USES_LICENSES		1
// TODO: Add new product's info here!
#endif

#ifdef PRODUCT_PROVISUAL_DEFINE
#define PRODUCT_NAME				"ProVisual"
#define PRODUCT_VERSION				"4.1"
#define PRODUCT_MAJOR_VERSION		4
#define PRODUCT_MINOR_VERSION		1
#define PRODUCT_SUBMINOR_VERSION	0
#define PRODUCT_VERSION_APPENDIX	""
#define PRODUCT_URL_NAME			"www.extravision.ca/provisual.htm"
#define PRODUCT_SUPPORT_URL_NAME	"support@extravision.com"
#define PRODUCT_COMPANY				"Extravision, Inc."
#define PRODUCT_COPYRIGHT			"Copyright (C) Extravision, Inc. 2005-2012"
#define PRODUCT_GUID				PRODUCT_GUID_PROVISUAL
#define PRODUCT_REBOOT_REQUIRED		0
#define PRODUCT_EXTRAVISION_REG_PREFIX	_T("http://www.extravision.ca/provisual/?product=")
#define PRODUCT_REGISTRATION_URL	PRODUCT_EXTRAVISION_REG_PREFIX _T("PROVISUAL") REGISTRATION_URL_ARGUMNETS
#define PRODUCT_PROTECTION_NAME		_T("ProVisual") g_szProductTrialStr
#define PRODUCT_SERIAL_PREFIX		_T("PROV")
#define PRODUCT_USES_LICENSES		1
// TODO: Add new product's info here!
#endif

#ifdef PRODUCT_SIGNIA_DEFINE
#define PRODUCT_NAME				"Signia Media"
#define PRODUCT_VERSION				"1.0.2"
#define PRODUCT_MAJOR_VERSION		1
#define PRODUCT_MINOR_VERSION		0
#define PRODUCT_SUBMINOR_VERSION	2
#define PRODUCT_VERSION_APPENDIX	""
#define PRODUCT_URL_NAME			"www.smart-avi.com/signia.shtml"
#define PRODUCT_SUPPORT_URL_NAME	PRODUCT_APPLICA_SUPPORT_URL_NAME
#define PRODUCT_COMPANY				PRODUCT_APPLICA_COMPANY
#define PRODUCT_COPYRIGHT			"Copyright (C) Applica, Inc. 2005-2012"
#define PRODUCT_GUID				PRODUCT_GUID_SIGNIA
#define PRODUCT_REBOOT_REQUIRED		0
#define PRODUCT_REGISTRATION_URL	PRODUCT_APPLICA_REG_PREFIX _T("SIGNIA") REGISTRATION_URL_ARGUMNETS
#define PRODUCT_PROTECTION_NAME		_T("Signia Media") g_szProductTrialStr
#define PRODUCT_SERIAL_PREFIX		_T("PSIG")
#define PRODUCT_USES_LICENSES		1
// TODO: Add new product's info here!
#endif

#ifdef PRODUCT_SIGNWALL_DEFINE
#define PRODUCT_NAME				"SignWALL"
#define PRODUCT_VERSION				"1.8.1"
#define PRODUCT_MAJOR_VERSION		1
#define PRODUCT_MINOR_VERSION		8
#define PRODUCT_SUBMINOR_VERSION	1
#define PRODUCT_VERSION_APPENDIX	""
#define PRODUCT_URL_NAME			"www.applica.com/product_SignWall.shtml"
#define PRODUCT_SUPPORT_URL_NAME	PRODUCT_APPLICA_SUPPORT_URL_NAME
#define PRODUCT_COMPANY				PRODUCT_APPLICA_COMPANY
#define PRODUCT_COPYRIGHT			"Copyright (C) Applica, Inc. 2005-2012"
#define PRODUCT_GUID				PRODUCT_GUID_SIGNWALL
#define PRODUCT_REBOOT_REQUIRED		0
#define PRODUCT_REGISTRATION_URL	PRODUCT_APPLICA_REG_PREFIX _T("SIGNWALL") REGISTRATION_URL_ARGUMNETS
#define PRODUCT_PROTECTION_NAME		_T("SignWALL") g_szProductTrialStr
#define PRODUCT_SERIAL_PREFIX		_T("PSIW")
#define PRODUCT_USES_LICENSES		1
#endif
// TODO: Add new product's info here!
//}}AXPDEL

// TODO: Add new product here!

#endif //ifndef PRODUCT_H_COMMON_DEFINES

// NSIS_COMMENT_START

#ifndef PRODUCT_H_COMMON_DEFINES

// Product Icon Configuration: (Applica: messages, mmc, services)

//{{AXPDEL
#ifdef PRODUCT_MANYPC_DEFINE
#define APPLICA_ICON MultiStationXP.ico
#define APPLICA_BMP MultiStationXP.bmp
#else
#ifdef PRODUCT_CVNET_DEFINE
#define APPLICA_ICON CVnet.ico
#define APPLICA_BMP CVnet.bmp
#else
#ifdef PRODUCT_MULTISTATION_DEFINE
#define APPLICA_ICON MultiStationXP.ico
#define APPLICA_BMP MultiStationXP.bmp
#else
#ifdef PRODUCT_ZEROLINK_DEFINE
#define APPLICA_ICON ZeroLinkXP.ico
#define APPLICA_BMP ZeroLinkXP.bmp
#else
#ifdef PRODUCT_APPLICASERVER_DEFINE
#define APPLICA_ICON ApplicaServer.ico
#define APPLICA_BMP ApplicaServer.bmp
#else
#ifdef PRODUCT_ZSERVER_DEFINE
#define APPLICA_ICON ZServer.ico
#define APPLICA_BMP ZServer.bmp
#else
//}}AXPDEL
#define APPLICA_ICON Applica.ico
#define APPLICA_BMP Applica.bmp
//{{AXPDEL
#endif
#endif
#endif
#endif
#endif
#endif
//}}AXPDEL

#if !defined PRODUCT_INFO_FOR_VERSIONINFO && !defined APSTUDIO_READONLY_SYMBOLS
#ifndef PRODUCT_NAME
//#ifndef PROTECTION_TOOL_PRJ
#error Bad PRODUCT_NAME define!
//#endif
#endif
#endif

#endif //ifndef PRODUCT_H_COMMON_DEFINES

//{{AXPDEL
// Registration dialog configuration:

#ifdef MESSAGES_PRJ
#include "resource.h"
#define PRODUCT_REG_MAIN_ICON
#define ASK_REBOOT_AFTER_PRODUCT_ACTIVATION
#define IDI_REG_ICON_ABOUT		IDI_APPLICA
#endif

#ifdef MESSAGES_IP_PRJ
#include "resource.h"
#define PRODUCT_REG_MAIN_ICON
#define ASK_REBOOT_AFTER_PRODUCT_ACTIVATION
#define IDI_REG_ICON_ABOUT		IDI_APPLICA
#endif

#ifdef PRESENTER_PRJ
#include "resource.h"
#define PRODUCT_REG_MAIN_ICON
#define IDI_REG_ICON_ABOUT		IDI_GENERAL
#endif

#ifdef PROTECTION_TOOL_PRJ
#include "resource.h"
#define PRODUCT_REG_MAIN_ICON
#define IDI_REG_ICON_ABOUT		IDR_MAINFRAME
#endif
//}}AXPDEL

#ifndef PRODUCT_H_COMMON_DEFINES

#undef PRODUCT_APPLIDEV_DEFINE
#undef PRODUCT_APPLICA_DEFINE
//{{AXPDEL
#undef PRODUCT_MANYPC_DEFINE
#undef PRODUCT_CVNET_DEFINE
#undef PRODUCT_MULTISTATION_DEFINE
#undef PRODUCT_ZEROLINK_DEFINE
#undef PRODUCT_APPLICASERVER_DEFINE
#undef PRODUCT_ZSERVER_DEFINE
#undef PRODUCT_PRESENTER_DEFINE
#undef PRODUCT_PRESENTER_SIGNAGE_DEFINE
#undef PRODUCT_PRESENTER_SIGNWARE_DEFINE
#undef PRODUCT_PRESENTER_WALL_DEFINE
#undef PRODUCT_PRESENTER_PRO_DEFINE
#undef PRODUCT_PRESENTER_3_DEFINE
#undef PRODUCT_PROVISUAL_DEFINE
#undef PRODUCT_IPCLONE_DEFINE
#undef PRODUCT_SNIFFER_DEFINE
#undef PRODUCT_SIGNIA_DEFINE
#undef PRODUCT_SIGNWALL_DEFINE
//}}AXPDEL
// TODO: Add new product here!

#endif //ifndef PRODUCT_H_COMMON_DEFINES

// NSIS_COMMENT_END
